# WireGuard config for ${node_name} — generated by Terraform.
# Private key generated at boot: wg genkey | tee /etc/wireguard/privatekey
# No private keys are stored in Terraform state (zero-trust).

[Interface]
Address    = ${wg_ip}
ListenPort = ${wg_port}
%{ for peer in peers ~}
[Peer]
# ${peer.name}
Endpoint   = ${peer.name}:${peer.wg_port}
AllowedIPs = ${peer.wg_ip}/32
%{ endfor ~}
